## Bag of Words (BoW)

In [1]:
import pandas as pd

In [27]:
df = pd.DataFrame({'text':['I start my my my day day with a cup of tea.','I study my AI course in',
                     'I do my breakfast after study', 'I take a nap at 2 pm']})

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [30]:
cv = CountVectorizer()

In [31]:
BoW = cv.fit_transform(df['text'])

In [16]:
BoW[0].toarray()

array([[0, 0, 0, 0, 0, 1, 2, 0, 3, 0, 1, 0, 1, 0, 0, 1, 1]])

In [32]:
cv.vocabulary_

{'start': 13,
 'my': 9,
 'day': 6,
 'with': 17,
 'cup': 5,
 'of': 11,
 'tea': 16,
 'study': 14,
 'ai': 1,
 'course': 4,
 'in': 8,
 'do': 7,
 'breakfast': 3,
 'after': 0,
 'take': 15,
 'nap': 10,
 'at': 2,
 'pm': 12}

In [23]:
cv.transform(['I study in the morning']).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0]])

## n-grams

In [34]:
cv1 = CountVectorizer(ngram_range=(2,2))

In [36]:
ngram = cv1.fit_transform(df['text'])

In [37]:
cv1.vocabulary_

{'start my': 15,
 'my my': 12,
 'my day': 11,
 'day day': 6,
 'day with': 7,
 'with cup': 18,
 'cup of': 5,
 'of tea': 14,
 'study my': 16,
 'my ai': 9,
 'ai course': 1,
 'course in': 4,
 'do my': 8,
 'my breakfast': 10,
 'breakfast after': 3,
 'after study': 0,
 'take nap': 17,
 'nap at': 13,
 'at pm': 2}

## TF-IDF 

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [39]:
tf = TfidfVectorizer()

In [40]:
tf.fit_transform(df['text']).toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.28097545, 0.5619509 , 0.        , 0.        , 0.53802897,
        0.        , 0.28097545, 0.        , 0.28097545, 0.        ,
        0.        , 0.28097545, 0.28097545],
       [0.        , 0.49819711, 0.        , 0.        , 0.49819711,
        0.        , 0.        , 0.        , 0.49819711, 0.31799276,
        0.        , 0.        , 0.        , 0.        , 0.39278432,
        0.        , 0.        , 0.        ],
       [0.49819711, 0.        , 0.        , 0.49819711, 0.        ,
        0.        , 0.        , 0.49819711, 0.        , 0.31799276,
        0.        , 0.        , 0.        , 0.        , 0.39278432,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.5       , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.5       , 0.        , 0.5       , 0.        , 0.        ,
        0.5       , 0.        , 0.        ]])

In [45]:
print(tf.get_feature_names_out())
print(tf.idf_)

['after' 'ai' 'at' 'breakfast' 'course' 'cup' 'day' 'do' 'in' 'my' 'nap'
 'of' 'pm' 'start' 'study' 'take' 'tea' 'with']
[1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073 1.22314355 1.91629073 1.91629073
 1.91629073 1.91629073 1.51082562 1.91629073 1.91629073 1.91629073]
